version: '2.4'

services:
  intellixwebcore:
    image: docuwarepublic.azurecr.io/intellix/app:${E_IntellixImageVersion}
    restart: unless-stopped
    tty: true
    networks:
      - intellixonpremise
    env_file: 
      - configuration.env
    ports:
      - 8080:80
    volumes:
      - ${E_FileStoragePath}:C:/FileStorage
    container_name: intellix_app
    depends_on:
      - intellixonpremisesolr

  intellixonpremisesolr:
    image: docuwarepublic.azurecr.io/intellix/solr:${E_SolRImageVersion}
    restart: unless-stopped
    tty: true
    networks:
      - intellixonpremise
    ports:
      - 8983:8983
    volumes:
      - ${E_SolRDataPath}:C:/solr/server/solr/productionWordPairExtended/data
    container_name: intellix_solr      
    mem_limit: 4G
    cpu_count: 2

networks:
  intellixonpremise:
    external:
      name: nat
